limit_req_zone $binary_remote_addr zone=main:10m rate=10r/s;

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location / {
        limit_req zone=main burst=20 nodelay;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        try_files /index.html =404;
    }
}
